M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2025-02-24T19:32:27+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-24T19:32:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X9.2252Y-5.3839
X9.2252Y-5.6114
T2
X9.2667Y-4.9803
T3
X9.0846Y-4.4626
X9.3209Y-4.4626
M30
