M48
; DRILL file {KiCad 9.0.7} date 2026-03-17T14:38:53-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-17T14:38:53-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.300
%
G90
G05
T1
X170.5Y-29.0
X176.28Y-29.0
T2
X105.75Y-39.76
T3
X104.75Y-60.26
X104.75Y-66.76
M30
